### ISSUE TITLE
flash install link broken on install

### ISSUE THREAD

**Issue by PaulPetring** [hzdr/thinstation#4]
```
--2017-03-09 11:51:48--  http://fpdownload.macromedia.com/get/flashplayer/pdc/11.2.202.569/install_flash_player_11_linux.i386.tar.gz
Resolving fpdownload.macromedia.com (fpdownload.macromedia.com)... 23.32.242.8
Connecting to fpdownload.macromedia.com (fpdownload.macromedia.com)|23.32.242.8|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-03-09 11:51:49 ERROR 404: Not Found.


Error has occured downloading file
Build Aborted
```

**Comment by jens-maus** [comment]
@PaulPetring Das ist momentan in der Tat leider ein problem weil die version anscheinend bei adobe nicht mehr zum download bereit liegt. Ich habe hier allerdings das binary lokal liegen und kann das gerne bereitstellen, dann muss man es nur 1x ins download Verzeichnis kopieren und gut ist. Alternative wäre eine direkte download URL zu der datei wieder irgendwo zu finden im netz bzw. eine neuere version zu finden.

**Comment by jens-maus** [comment]
Sollte inzwischen repariert sein.
