### ISSUE TITLE
missing dirs on install 

### ISSUE THREAD

**Issue by PaulPetring** [hzdr/thinstation#5]
`cp: target '/tftpboot/thinstation/conf/pkg/' is not a directory`

`'ts/build/boot-images/pxe/boot/'`  not created during regular install

FIX: `mkdir -p ts/build/boot-images/pxe/boot/ `
FIX: `mkdir -p /tftpboot/thinstation/conf/pkg/`

Thx in advance

**Comment by jens-maus** [comment]
@PaulPetring Diese mkdir -p aufruf könnte man kurzerhand in das "mkhzdr" Skript reinmachen. Allerdings würde ich das mkhzdr ohnehin hier/da gerne gegen ein Makefile ersetzen wo man dann selbst "make install" machen kann und er installiert das dann entsprechend. Ich denke das wäre der bessere weg.

**Comment by PaulPetring** [comment]
Sobald ich es zum laufen bekommen habe, können wir über einen sauberen Weg nachdenken. Gerade kämpfe ich noch gegen das Hängenbleiben im Splashscreen bei 90%. Dieser Fehler tritt im Moment übrigends auch bei der existierenden Buildumgebung bei mir auf. Aber ich bin dran.
